[package]
edition = "2024"
name = "nfc-app-hackxpansion"
version = "0.1.0"
license = "GPL-3.0"
description = "NFC Writer app for the Hackxpansion console's nfcxpansion module."
repository = "https://github.com/Las-Vejas/nfc-app-hackxpansion"

[dependencies]
xpanse-api = "0.2.3"
slint = { version = "1.17", default-features = false, features = [
  "compat-1-2",
  "unsafe-single-threaded",
  "libm",
  "renderer-software",
] }

[build-dependencies]
slint-build = "1.17"
